### PR TITLE
Kp824 patch 1

### PR DESCRIPTION
**Pull request by KP824**
Adding pull request template for project

### CODE REVIEW

**Review by heyitsmattox — COMMENTED** [review]
Should we merge these into `dev` rather then main?

**Comment by KP824** [comment]
> Should we merge these into `dev` rather then main?

Great question Matt. This will add the pull request template for all the children branches of main. We want the template to exist when we make a pull request to main branch as well.

**Comment by heyitsmattox** [comment]
Ah, I guess I was confused on the 26 file changes and got worried. Unless you grabbed Jenny's latest changes and are just adding onto them. Is that why there are so many files being changed? 

Otherwise, it looks good here.

**Comment by KP824** [comment]
Yes, I am adding to dev branch. Main does not have any of the changes from dev, and it look it's that's what all the changes for.

**Review by heyitsmattox — APPROVED** [review]
Looks good on my end.

**Pull request merged**
